// Generated by CoffeeScript 1.6.3
(function() {
  var Article, app, article, express;

  express = require('express');

  Article = require('./article_provider').Article;

  app = express();

  app.configure(function() {
    app.set('views', "" + __dirname + "/views");
    app.set('view engine', 'jade');
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(require('stylus').middleware({
      src: "" + __dirname + "/public"
    }));
    app.use(app.router);
    return app.use(express["static"]("" + __dirname + "/public"));
  });

  article = new Article('localhost', 27017);

  app.get('/', function(req, res) {
    console.log("Routing request");
    return article.find_all(function(error, docs) {
      return res.render('index.jade', {
        title: 'Blog',
        articles: docs
      });
    });
  });

  app.get('/blog/new', function(req, res) {
    return res.render('blog_new.jade', {
      title: 'New Article'
    });
  });

  app.post('/blog/new', function(req, res) {
    console.log("Saving article with params:\n    title: " + (req.param('title')) + "\n    body: " + (req.param('body')));
    return article.save({
      title: req.param('title'),
      body: req.param('body')
    }, function(error, docs) {
      return res.redirect('/');
    });
  });

  app.get('/blog/:id', function(req, res) {
    console.log("Showing page for id: " + req.params.id);
    return article.find_by_id(req.params.id, function(error, article) {
      return res.render('blog_show.jade', {
        title: article.title,
        article: article
      });
    });
  });

  app.listen(3000);

}).call(this);
