// Generated by CoffeeScript 1.6.3
(function() {
  var Chat, MongoClient, chat, connect_url, format;

  MongoClient = require('mongodb').MongoClient;

  format = require('util').format;

  connect_url = 'mongodb://127.0.0.1:27017/nodejs';

  Chat = function() {};

  Chat.prototype.get_collection = function(callback) {
    return MongoClient.connect(connect_url, function(err, db) {
      var collection;
      if (err) {
        throw err;
      }
      collection = db.collection('chat');
      callback(null, collection);
      return db.close();
    });
  };

  Chat.prototype.all = function(callback) {
    console.log("beginning the 'all' request for Users");
    return this.get_collection(function(err, collection) {
      if (err) {
        throw err;
      }
      return callback(null, collection.find().toArray);
    });
  };

  Chat.prototype.create = function(obj, callback) {
    return this.get_collection(function(err, collection) {
      if (err) {
        throw err;
      }
      return this.get_collection.insert(obj, function(err, docs) {
        if (err) {
          throw err;
        }
        return callback(null, docs);
      });
    });
  };

  chat = new Chat();

  console.log("starting script!");

  chat.all(function(err, results) {
    return console.dir(results);
  });

  chat.create({
    name: "John Smith"
  }, function(err, docs) {
    return console.dir(docs);
  });

  console.error("hitting end of script");

  exports.Chat = Chat;

}).call(this);
