// Generated by CoffeeScript 1.6.3
(function() {
  var route;

  route = function(pathname) {
    return console.log("About to route a request for: " + pathname);
  };

  exports.route = route;

}).call(this);
